service: solutions-article-info-api
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
